name: Pull and Save Docker Image
on:
  workflow_dispatch:
    inputs:
      image:
        description: Docker image name
        required: true
        default: 'alpine:latest'
      arch:
        type: choice
        description: Select OS/ARCH
        options:
        - linux/amd64
        - linux/arm64
        - linux/arm/v7
        
jobs:
  pull_and_package:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Pull Docker Images
      run: |
        docker pull "${{ github.event.inputs.image }}" --platform "${{ github.event.inputs.arch }}"

    - name: Upload image
      uses: ishworkh/container-image-artifact-upload@v2.0.0
      with:
        image: "${{ github.event.inputs.image }}"
        retention_days: "1"